# Secret security scan
name: Secret security scan

on:
  workflow_call:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security scan
    steps:
      - uses: actions/checkout@v3
      - name: scan-secrets
        run: |
          DOCKER_USER_ID="$(id -u)"
          docker image pull zricethezav/gitleaks:v8.8.4
          docker run -u ${DOCKER_USER_ID} -v ${GITHUB_WORKSPACE}:/path zricethezav/gitleaks:v8.8.4 detect --source="/path" -v