# Builds a package using Maven and then publishes it to GitHub packages

name: Publish Java Artifact

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'Github Token'
        required: true
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'
        
jobs:
  publish-java-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}