# Builds a java war artifact using gradle
name: Build Java War using Gradle

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'

jobs:
  build-war:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build War
        run: ./gradlew bootWar --parallel
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/*.war