# Runs java application tests using gradle
name: Test Java using Gradle

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '17'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      TASK:
        description: 'Test task name'
        required: false
        type: string
        default: 'test'
      COVERAGE:
        description: 'Generate and upload tests report (w/ coverage)'
        required: false
        type: boolean
        default: true
      TIMEOUT:
        required: false
        type: number
        default: 30

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Tests
        run: ./gradlew ${{ inputs.TASK }} --parallel
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport --parallel
        if: ${{ inputs.COVERAGE }}
      - name: Tar Report Files
        run: cd build && zip -r $OLDPWD/coverage_report.zip classes/ reports/
        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage_report.zip
        if: always()