# Analyzes a java project using sonar with gradle
name: Analyze Java using Gradle

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonar Token'
        required: true
    inputs:
      SONAR_URL:
        description: 'Sonar Host Url'
        required: false
        type: string
        default: 'https://sonarcloud.io'
      SONAR_ORGANIZATION:
        description: 'Sonar organization'
        required: false
        type: string
        default: 'aegro-github'
      SONAR_SOURCE_ENCODING:
        description: 'Sonar source encoding'
        required: false
        type: string
        default: 'UTF-8'
      SONAR_PROJECT_KEY:
        description: 'Sonar project key'
        required: false
        type: string
      SONAR_PROJECT_NAME:
        description: 'Sonar project name'
        required: false
        type: string
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'

jobs:
  analyze-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Create build directorie
        run: |
          mkdir -p build/sonar
      - uses: actions/download-artifact@v2
        with:
          name: coverage_report
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq coverage_report.zip -d build
      - name: Run Sonar Analysis
        run: |
          ./gradlew sonarqube -x compileJava -x compileTestJava -Dsonar.host.url=${{ inputs.SONAR_URL }} -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectName=${{ inputs.SONAR_PROJECT_NAME }} -Dsonar.organization=${{ inputs.SONAR_ORGANIZATION }} --parallel --stacktrace --info