# Runs java application tests with redis service using gradle
name: Test Java with Redis using Gradle

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '17'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      TASK:
        description: 'Test task name'
        required: false
        type: string
        default: 'test'
      COVERAGE:
        description: 'Generate and upload tests report (w/ coverage)'
        required: false
        type: boolean
        default: true
      TIMEOUT:
        required: false
        type: number
        default: 30

env:
  USERNAME_GIT: aegro-github-bot
  TOKEN_GIT: ${{ secrets.PKG_GITHUB_TOKEN }}

jobs:
  gradle-test_with_redis:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Tests
        run: ./gradlew ${{ inputs.TASK }} --parallel
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport --parallel
        if: ${{ inputs.COVERAGE }}
      - name: Tar Report Files
        run: cd build && zip -r $OLDPWD/coverage_report.zip classes/ reports/
        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage_report.zip
        if: always()