name: Test Java using Maven

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '17'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      TASK:
        description: 'Test task name'
        required: false
        type: string
        default: 'test'
      TIMEOUT:
        required: false
        type: number
        default: 30
      JAVA_PATH:
        description: 'Java path'
        required: false
        type: string
        default: '$PWD'

env:
  USERNAME_GIT: ${{ secrets.PKG_GITHUB_USERNAME }}
  TOKEN_GIT: ${{ secrets.PKG_GITHUB_TOKEN }}

jobs:
  maven-test:
    name: Maven test
    timeout-minutes: ${{ inputs.TIMEOUT }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ inputs.JAVA_PATH }}
          mvn --batch-mode ${{ inputs.TASK }}