# Analyzes a java project using sonar with gradle
name: Analyze Java using Gradle

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonar Token'
        required: true
    inputs:
      SONAR_URL:
        description: 'Sonar Host Url'
        required: false
        type: string
        default: 'https://sonarcloud.io'
      SONAR_ORGANIZATION:
        description: 'Sonar organization'
        required: false
        type: string
        default: 'aegro'
      SONAR_SOURCE_ENCODING:
        description: 'Sonar source encoding'
        required: false
        type: string
        default: 'UTF-8'
      SONAR_PROJECT_KEY:
        description: 'Sonar project key'
        required: false
        type: string
      SONAR_PROJECT_NAME:
        description: 'Sonar project name'
        required: false
        type: string
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'

jobs:
  analyze-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage_report
      - name: Run Sonar Analysis
        run: |
          ./gradlew sonarqube -x compileJava -x compileTestJava --parallel
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ inputs.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}