# Runs java application tests using gradle and mongo
name: Test Java with Gradle and mongo

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'

jobs:
  test-with-mongo:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
        - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Tests
        run: ./gradlew test --stacktrace --parallel
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport --parallel
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: |
            build/classes/**
            build/reports/**