# Runs java application tests with redis service using gradle
name: Test Java with Redis using Gradle

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'
      TIMEOUT:
        required: false
        type: number
        default: 30
      TEST-ENV:
        description: 'Test Environment'
        required: false
        type: string
        default: 'test'

jobs:
  test-with-redis:
    environment: ${{ inputs.TEST-ENV }}
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Tests
        run: ./gradlew test --stacktrace --parallel
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport --parallel
      - name: Tar files
        run: cd build && zip -r $OLDPWD/coverage_report.zip classes/ reports/
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage_report.zip