# Builds a java war artifact using gradle
name: Build Java War using Gradle

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '17'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      TIMEOUT:
        required: false
        type: number
        default: 15

jobs:
  gradle-build_war:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build War
        run: ./gradlew bootWar --parallel
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/*.war