# Analyzes a java project using sonar with gradle
name: Analyze Java using Gradle

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Sonar Token'
        required: true
    inputs:
      JAVA_VERSION:
        description: 'Java version'
        required: false
        type: string
        default: '16'
      JAVA_DISTRIBUTION:
        description: 'Java distribution'
        required: false
        type: string
        default: 'adopt'

jobs:
  analyze-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Sonar Analysis
        run: ./gradlew sonarqube -Dsonar.login="${{ secrets.SONAR_TOKEN }}" -x compileJava -x compileTestJava --parallel