name: Notify Deploy

on:
  workflow_call:
    secrets:
      VELOCITY_TOKEN:
        description: 'Velocity Token'
        required: true
    inputs:
      ENVIRONMENT:
        description: 'Environment of deployed app'
        required: true
        type: string
        
jobs:
  velocity:
    runs-on: ubuntu-latest
    steps:
      - name: Velocity Deployment Notify
        run: |
            curl --fail https://velocity.codeclimate.com/deploys \
            -d "token=${{ secrets.VELOCITY_TOKEN }}" \
            -d "repository_url=${{ github.server_url }}/${{ github.repository }}" \
            -d "environment=${{ inputs.ENVIRONMENT }}" \
            -d "revision=${{ github.sha }}" \
            -d "version=${{ github.sha }}"