name: Notify Deploy

on:
  workflow_call:
    secrets:
      SLACK_TOKEN:
        description: 'Slack Token'
        required: false
      NR_API_KEY:
        description: 'New Relic API KEY'
        required: false
      NR_ACCOUNT_ID:
        description: 'New Relic account ID'
        required: false
      VELOCITY_TOKEN:
        description: 'Velocity Token'
        required: false
    inputs:
      PREVIOUS_RESULT:
        description: 'Result from previous job(s)'
        required: true
        type: string
      SLACK_CHANNEL:
        description: 'Slack channel to notify'
        required: false
        type: string
      NR_APP_ID:
        description: 'New Relic application ID'
        required: false
        type: string
      ENVIRONMENT:
        description: 'Environment of deployed app (for velocity)'
        required: false
        type: string
      DESCRIPTION:
        description: 'Description of deployed version'
        required: false
        type: string
        
jobs:
  notify-slack:
    if: ${{ inputs.SLACK_CHANNEL != '' }}
    uses: ./.github/workflows/notify-deploy_slack.yml
    secrets: inherit
    with:
      PREVIOUS_RESULT: ${{ inputs.PREVIOUS_RESULT }}
      SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
  notify-nr:
    if: ${{ inputs.PREVIOUS_RESULT != 'failure' && inputs.NR_APP_ID != '' }}
    uses: ./.github/workflows/notify-deploy_NR.yml
    secrets: inherit
    with:
      NR_APP_ID: ${{ inputs.NR_APP_ID }}
      DESCRIPTION: ${{ inputs.DESCRIPTION }}
  notify-velocity:
    if: ${{ inputs.PREVIOUS_RESULT != 'failure' && inputs.ENVIRONMENT != '' }}
    uses: ./.github/workflows/notify-deploy_velocity.yml
    secrets: inherit
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}