# Reports deployment info to new relic
name: Report Deploy

on:
  workflow_call:
    secrets:
      NR_API_KEY:
        description: 'New Relic API KEY'
        required: true
    inputs:
      NR_ENTITY_GUID:
        description: 'New Relic entity GUID'
        required: true
        type: string
      VERSION:
        description: 'Version of deployed app'
        required: false
        type: string
      DESCRIPTION:
        description: 'Description of deployed version'
        required: false
        type: string
        
jobs:
  new-relic:
    runs-on: ubuntu-latest
    steps:
      - name: New Relic Deployment Report
        uses: newrelic/deployment-marker-action@v2.2.0
        with:
          apiKey: ${{ secrets.NR_API_KEY }}
          guid: ${{ inputs.NR_ENTITY_GUID }}
          version: ${{ inputs.VERSION || inputs.github.sha }}
          description: ${{ inputs.DESCRIPTION }}