# Reports deployment to slack (even in case of failure)
name: Report Deploy

on:
  workflow_call:
    secrets:
      SLACK_TOKEN:
        description: 'Slack Token'
        required: true
    inputs:
      FAILURE:
        description: 'Indicates if previous job(s) failed'
        required: true
        type: boolean
      SLACK_CHANNEL:
        description: 'Slack channel to report'
        required: true
        type: string
      TIMEOUT:
        required: false
        type: number
        default: 5        
jobs:
  slack:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    steps:
      - name: Report Success
        if: ${{ !inputs.FAILURE }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ inputs.SLACK_CHANNEL }}
          status: SUCCESS
          color: good
      - name: Report Failure
        if: ${{ inputs.FAILURE }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ inputs.SLACK_CHANNEL }}
          status: FAILED
          color: danger