# Reports deployment to our main monitoring tools
# To ignore slack, don't pass slack_channel
# To ignore new relic, don't pass nr_app_id
# To ignore velocity, don't pass environment
name: Report Deploy

on:
  workflow_call:
    secrets:
      SLACK_TOKEN:
        description: 'Slack Token'
        required: false
      NR_API_KEY:
        description: 'New Relic API KEY'
        required: false
      VELOCITY_TOKEN:
        description: 'Velocity Token'
        required: false
    inputs:
      FAILURE:
        description: 'Indicates if previous job(s) failed'
        required: true
        type: boolean
      SLACK_CHANNEL:
        description: 'Slack channel to report'
        required: false
        type: string
      NR_ENTITY_GUID:
        description: 'New Relic entity GUID'
        required: false
        type: string
      ENVIRONMENT:
        description: 'Environment of deployed app (for velocity)'
        required: false
        type: string
      VERSION:
        description: 'Version of deployed app'
        required: false
        type: string
      DESCRIPTION:
        description: 'Description of deployed version'
        required: false
        type: string
        
jobs:
  slack:
    if: ${{ inputs.SLACK_CHANNEL != '' }}
    uses: ./.github/workflows/report_deploy-slack.yml
    secrets: inherit
    with:
      FAILURE: ${{ inputs.FAILURE }}
      SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
  new-relic:
    if: ${{ !inputs.FAILURE && inputs.NR_ENTITY_GUID != '' }}
    uses: ./.github/workflows/report_deploy-NR.yml
    secrets: inherit
    with:
      NR_ENTITY_GUID: ${{ inputs.NR_ENTITY_GUID }}
      VERSION: ${{ inputs.VERSION }}
      DESCRIPTION: ${{ inputs.DESCRIPTION }}
  velocity:
    if: ${{ !inputs.FAILURE && inputs.ENVIRONMENT != '' }}
    uses: ./.github/workflows/report_deploy-velocity.yml
    secrets: inherit
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}