name: Secrets security scan

on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
          description: 'Organization gitleaks license'
          required: true

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    name: gitleaks
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}