name: Secrets security scan

on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
          description: 'Organization gitleaks license'
          required: true

jobs:
  scan_secrets:
    runs-on: ubuntu-latest
    name: gitleaks
    steps:
      - uses: actions/checkout@v4
      - name: scan-secrets
        run: |
          DOCKER_USER_ID="$(id -u)"
          docker image pull zricethezav/gitleaks:v8.18.0
          docker run -u ${DOCKER_USER_ID} -v ${GITHUB_WORKSPACE}:/path zricethezav/gitleaks:v8.18.0 detect --source="/path" -v
      # - uses: gitleaks/gitleaks-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}