# K8s manifests updade
name: Manifests updade image

on:
  workflow_call:
    inputs:
      REPO:
        description: 'ECR repository name'
        required: true
        type: string
      SERVICE_NAME:
        description: 'Service name'
        required: true
        type: string
      TIMEOUT:
        required: false
        type: number
        default: 5

jobs:
  update_image_manifest:
    environment: staging
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    name: Update manifests
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-tag
      - run: |
          TEAM="$(echo $GITHUB_REF_NAME |sed 's/^test\///')"
          TIMESTAMP="$(cat job.output | awk 'NR==1')"
          echo ${TEAM}
          sed -i "s/${{ inputs.REPO }}:.*/${{ inputs.REPO }}:${TIMESTAMP}/g" k8s-deploy/${{inputs.SERVICE_NAME}}/values-${TEAM}-test.yaml
          git add k8s-deploy/${{inputs.SERVICE_NAME}}/values-${TEAM}-test.yaml
          git config user.name "aegro-github-bot"
          git config user.email github@aegro.com.br
          git commit -m "[skip ci] Update manifests"
          git push origin ${GITHUB_REF_NAME}